import { Be_Vietnam_Pro } from 'next/font/google';
import './globals.css';

// Khởi tạo phông chữ với subset tiếng Việt và gán vào một CSS variable
const beVietnamPro = Be_Vietnam_Pro({
  subsets: ['vietnamese', 'latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-be-vietnam-pro', // Tên biến CSS để dùng trong Tailwind
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // Thêm biến CSS của phông chữ vào thẻ html
    <html lang="vi" className={beVietnamPro.variable}>
      {/* Mặc định áp dụng font-sans cho toàn bộ body */}
      <body className="font-sans antialiased">
        {children}
      </body>
    </html>
  );
}